version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    ports:
      - 8080:8080
    network_mode: "host"
    environment:
      - KAFKA_ADDRESS=localhost:9092
      - TOPIC_NAME=NEW_MESSAGE
    volumes:
      - ${APPLICATION_ROOT_FOLDER}/producer:/usr/src/mymaven
      - ${MAVEN_SETTINGS_FOLDER}:/var/maven/.m2
    user: 1000:1000

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    network_mode: "host"
    environment:
      - KAFKA_ADDRESS=localhost:9092
      - TOPIC_NAME=NEW_MESSAGE
    volumes:
      - ${APPLICATION_ROOT_FOLDER}/consumer:/usr/src/mymaven
      - ${MAVEN_SETTINGS_FOLDER}:/var/maven/.m2
    user: 1000:1000

